---
:gems:
  :name: Gems
  :title: Ruby Gems
  :category: gems
  :list:
    - rake
    -
      :name: bundler
      :version: "1.15.3"
    -
      :name: rails
      :version: "5.1.3"
    -
      :name: activerecord-sqlserver-adapter
      :version: "5.1.1"
    - tiny_tds
    - sqlite3
    - sqlite3-ruby
    - rubyzip
    - rb-readline
    -
      :name: coffee-rails
      :version: "4.2.2"
    -
      :name: jquery-rails
      :version: "4.3.1"
    -
      :name: sass-rails
      :version: "5.0.6"

:msvc_runtime:
  :name: MsvcRuntime
  :title: Microsoft Visual C Runtime
  :category: component
  :regex: '^.*$'
  :url: "http://download.microsoft.com/download/d/d/9/dd9a82d0-52ef-40db-8dab-795376989c03/vcredist_x86.exe"

:dev_kit:
  :name: DevKit
  :title: Development Kit
  :category: component
  :regex: '^.*$'
  :target: 'DevKit'
  :url: "http://s3.amazonaws.com/railsinstaller/Resources/DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe"

:ruby233:
  :category: component
  :title: Ruby 2.3.3
  :name: Ruby233
  :regex: '^.*$'
  :url: "http://dl.bintray.com/oneclick/rubyinstaller/ruby-2.3.3-i386-mingw32.7z"
  :rename: Ruby2.3.3

:git:
  :category: component
  :title: Git 2.21.0
  :name: Git
  :url: "https://github.com/git-for-windows/git/releases/download/v2.21.0.windows.1/PortableGit-2.21.0-32-bit.7z.exe"
  :target: "Git"
  :regex: '^.*$'

:pg:
  :category: gem
  :name: Pg
  :dlls:
    - postgresql/lib/libpq.dll
  :configure:
    - --with-pg-config="{{stage_path}}/postgresql/bin/pg_config"

:postgresql_server:
  :category: component
  :title: PostgreSQL Server
  :name: PostgresServer
  :files:
    - libpq.dll
    - ssleay32.dll
    - libeay32.dll
    - libintl-8.dll
    - msvcr90.dll
    - libxml2.dll
  :regex: '^.*$'
  :url: "http://get.enterprisedb.com/postgresql/postgresql-9.3.5-1-windows-binaries.zip"

:rails:
  :name: Rails
  :title: Rails 3 sample application
  :category: gem

:rails_todo:
  :name: RailsTodo
  :title: Rails 3 Todo Sample application
  :category: gem

:rails_docs:
  :name: RailsDocs
  :title: Rails 3 Documentation
  :category: component

:rails_guides:
  :name: RailsGuides
  :title: Rails 3 Guides
  :category: component

:ruby_docs:
  :name: RubyDocs
  :title: Ruby Documentation
  :category: component

:sqlite3:
  :name: Sqlite3
  :title: Sqlite3
  :category: component
  :files:
    - sqlite3.dll
    - sqlite3.def
    - sqlite3.exe
  :regex: '^.+\.exe$'
  :url: http://sqlite.org/2014/sqlite-shell-win32-x86-3080702.zip

:sqlite3_dll:
  :name: Sqlite3Dll
  :title: Sqlite3 Dll
  :category: component
  :regex: '^.+\.dll$'
  :url: http://sqlite.org/2014/sqlite-dll-win32-x86-3080702.zip

:ssl_certificates:
  :name: SSLCertificates
  :title: Certificates
  :category: component
  :url: http://curl.haxx.se/ca
  :file: cacert.pem

:mysql_gem:
  :name: Mysql
  :title: MySQL Gem
  :category: component
  :dlls:
    - mysql/lib/libmysql.dll
  :configure:
    - --with-mysql-config="{{stage_path}}/mysql/bin/mysql_config"

:mysql_server:
  :name: MySQLServer
  :title: MySQL Community Server
  :category: component
  :url: "http://mysql.mirrors.pair.com/Downloads/MySQL-5.6/mysql-5.6.21-winx64.zip"
  :regex: '^.*$'
  :urls:
    - "http://mysql.mirrors.pair.com/Downloads/MySQL-5.6/mysql-5.6.21-winx64.zip"
    - "http://mysql.mirrors.pair.com/Downloads/MySQL-5.6/mysql-5.6.21-win32.zip"

:bsdtar:
  :name: BSDTar
  :title: Basic BSDTar
  :category: utility
  :target: bin
  :binary: "basic-bsdtar.exe"
  :regex: '^basic-bsdtar.exe$'
  :url: "http://downloads.sourceforge.net/mingw/basic-bsdtar-2.8.3-1-mingw32-bin.zip"

:sevenzip:
  :name: SevenZip
  :title: 7Zip
  :category: utility
  :target: bin
  :binary: "7za.exe"
  :regex: '^7za\.exe$'
  :url: "http://downloads.sourceforge.net/project/sevenzip/7-Zip/9.20/7za920.zip"
